version: 2

enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/android/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directories:
    - "/.github/workflows"
    - "/.github/actions/android"
    - "/.github/actions/common"
    - "/.github/actions/ios"
    - "/.github/actions/screenshot-android"
    schedule:
      interval: "daily"