name: Badge Magic PR CI

on:
  pull_request:
    branches: [ "flutter_app" ]

env:
  ANDROID_EMULATOR_API: 34
  ANDROID_EMULATOR_ARCH: x86_64
  IPHONE_DEVICE_MODEL: iPhone 16 Pro Max
  IPAD_DEVICE_MODEL: iPad Pro 13-inch (M4)

jobs:
  common:
    name: Common Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Common Workflow
        uses: ./.github/actions/common

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/

  android:
    name: Android Flutter Build
    needs: common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Android Workflow
        uses: ./.github/actions/android

  ios:
    name: iOS Flutter Build
    needs: common
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: iOS Workflow
        uses: ./.github/actions/ios

  screenshots-android:
    name: Screenshots (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Android Screenshot Workflow
        uses: ./.github/actions/screenshot-android
        with:
          ANDROID_EMULATOR_API: ${{ env.ANDROID_EMULATOR_API }}
          ANDROID_EMULATOR_ARCH: ${{ env.ANDROID_EMULATOR_ARCH }}

  screenshots-ios:
    name: Screenshots (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: iOS Screenshot Workflow
        uses: ./.github/actions/screenshot-ios
        with:
          IPHONE_DEVICE_MODEL: ${{ env.IPHONE_DEVICE_MODEL }}
          IPAD_DEVICE_MODEL: ${{ env.IPAD_DEVICE_MODEL }}
      